"""add models

Revision ID: 64e50d24d5c0
Revises: 2b91e3e2de66
Create Date: 2025-02-17 11:45:20.885324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64e50d24d5c0'
down_revision: Union[str, None] = '2b91e3e2de66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('admin_id', sa.String(length=36), nullable=False),
    sa.Column('admin_username', sa.String(length=255), nullable=True),
    sa.Column('admin_email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('admin_email'),
    sa.UniqueConstraint('admin_username'),
    sa.UniqueConstraint('password')
    )
    op.create_table('event',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('user_fid', sa.String(length=255), nullable=False),
    sa.Column('event', sa.Text(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_fid'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('post',
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('post_caption', sa.Text(), nullable=True),
    sa.Column('post_image', sa.Text(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_table('comment',
    sa.Column('comment_id', sa.String(length=36), nullable=False),
    sa.Column('post_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.post_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_table('like',
    sa.Column('like_id', sa.String(length=36), nullable=False),
    sa.Column('post_id', sa.String(length=255), nullable=False),
    sa.Column('user_id_like', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.post_id'], ),
    sa.ForeignKeyConstraint(['user_id_like'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('like_id')
    )
    op.create_table('request',
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('post_id_self', sa.String(length=36), nullable=False),
    sa.Column('user_id_connection', sa.String(length=36), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_accepted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['post_id_self'], ['post.post_id'], ),
    sa.ForeignKeyConstraint(['user_id_connection'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('connection',
    sa.Column('connection_id', sa.String(length=36), nullable=False),
    sa.Column('user_id_self', sa.String(length=255), nullable=False),
    sa.Column('user_id_connection', sa.String(length=255), nullable=False),
    sa.Column('request_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['request.request_id'], ),
    sa.ForeignKeyConstraint(['user_id_connection'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['user_id_self'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('connection_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('connection')
    op.drop_table('request')
    op.drop_table('like')
    op.drop_table('comment')
    op.drop_table('post')
    op.drop_table('event')
    op.drop_table('admin')
    # ### end Alembic commands ###
