"""remove comment col in Request

Revision ID: 757b88cd8cf7
Revises: 94f69477e1b0
Create Date: 2025-02-18 19:19:06.015827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '757b88cd8cf7'
down_revision: Union[str, None] = '94f69477e1b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'comment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('comment', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
