"""modify Request Model

Revision ID: 86344092b8ad
Revises: 757b88cd8cf7
Create Date: 2025-02-18 19:26:11.385815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '86344092b8ad'
down_revision: Union[str, None] = '757b88cd8cf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('user_id_self', sa.String(length=36), nullable=False))
    op.alter_column('request', 'is_accepted',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.drop_constraint('request_ibfk_2', 'request', type_='foreignkey')
    op.drop_constraint('request_ibfk_1', 'request', type_='foreignkey')
    op.create_foreign_key(None, 'request', 'user', ['user_id_connection'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'request', 'user', ['user_id_self'], ['user_id'], ondelete='CASCADE')
    op.drop_column('request', 'post_id_self')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('post_id_self', mysql.VARCHAR(length=36), nullable=False))
    op.drop_constraint(None, 'request', type_='foreignkey')
    op.drop_constraint(None, 'request', type_='foreignkey')
    op.create_foreign_key('request_ibfk_1', 'request', 'post', ['post_id_self'], ['post_id'])
    op.create_foreign_key('request_ibfk_2', 'request', 'user', ['user_id_connection'], ['user_id'])
    op.alter_column('request', 'is_accepted',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.drop_column('request', 'user_id_self')
    # ### end Alembic commands ###
