"""empty message

Revision ID: 8772e0ab3586
Revises: 
Create Date: 2025-01-21 14:35:12.468187

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8772e0ab3586'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('user_email')
        batch_op.drop_index('user_fid')
        batch_op.drop_index('user_name')
        batch_op.drop_index('user_sid')

    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('user_sid', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('user_fid', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('user_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('user_email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('user_password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('is_valid', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('user_sid', ['user_sid'], unique=True)
        batch_op.create_index('user_name', ['user_name'], unique=True)
        batch_op.create_index('user_fid', ['user_fid'], unique=True)
        batch_op.create_index('user_email', ['user_email'], unique=True)

    # ### end Alembic commands ###
